= Jackson

Since domain-primitives are complex objects, (not primitives from a language perspective), they would usually serialize
to JSON as objects rather than values, which just creates overhead on the wire and makes consumption more complex.

This generator registers a custom Jackson module which will make sure that each domain-primitive is serialized as a
simple value and deserializing uses the proper construction method.

Since there are subtle differences from Jackson-2 to Jackson-3, Lazyval ships two dedicated generators for Java as well
as Kotlin.

When wrapping another type (like LocalDate), the implementation will look up already registered and configured
de-/serializers.

== Config Options

|===
|Property |Description

|_lazyval.jackson.package_
|Specifies the package where the `LazyvalJacksonModule` interface is generated to.
Overrides `lazyval.generators.basePackage`.

|===

== Generated Files

[tabs]
====
Java (Jackson 2.x)::
+
[source, java]
----
public class LazyvalJacksonModule extends SimpleModule {
  @Override
  public void setupModule(Module.SetupContext context) {
    super.setupModule(context);
    SimpleSerializers sers = new SimpleSerializers();
    SimpleDeserializers desers = new SimpleDeserializers();
    sers.addSerializer(OrderDate.class, OrderDateSerializer.INSTANCE);
    sers.addSerializer(Quantity.class, QuantitySerializer.INSTANCE);
    desers.addDeserializer(OrderDate.class, OrderDateDeserializer.INSTANCE);
    desers.addDeserializer(Quantity.class, QuantityDeserializer.INSTANCE);
    context.addSerializers(sers);
    context.addDeserializers(desers);
  }

  static class OrderDateSerializer extends StdSerializer<OrderDate> {
    static final OrderDateSerializer INSTANCE = new OrderDateSerializer();

    protected OrderDateSerializer() {
      super(OrderDate.class);
    }

    @Override
    public void serialize(OrderDate value, JsonGenerator gen, SerializerProvider provider) throws
        IOException {
      var ser = provider.findValueSerializer(LocalDate.class);
      ser.serialize(value.date(), gen, provider);
    }
  }

  static class QuantitySerializer extends StdSerializer<Quantity> {
    static final QuantitySerializer INSTANCE = new QuantitySerializer();

    protected QuantitySerializer() {
      super(Quantity.class);
    }

    @Override
    public void serialize(Quantity value, JsonGenerator gen, SerializerProvider provider) throws
        IOException {
      gen.writeNumber(value.value());
    }
  }

  static class OrderDateDeserializer extends StdDeserializer<OrderDate> {
    static final OrderDateDeserializer INSTANCE = new OrderDateDeserializer();

    protected OrderDateDeserializer() {
      super(OrderDate.class);
    }

    @Override
    public OrderDate deserialize(JsonParser p, DeserializationContext ctxt) throws IOException,
        JacksonException {
      var deser = ctxt.findContextualValueDeserializer(ctxt.constructType(LocalDate.class), null);
      var value = (LocalDate) deser.deserialize(p, ctxt);
      return new OrderDate(value);
    }
  }

  static class QuantityDeserializer extends StdDeserializer<Quantity> {
    static final QuantityDeserializer INSTANCE = new QuantityDeserializer();

    protected QuantityDeserializer() {
      super(Quantity.class);
    }

    @Override
    public Quantity deserialize(JsonParser p, DeserializationContext ctxt) throws IOException,
        JacksonException {
      var value = p.getValueAsInt();
      return new Quantity(value);
    }
  }
}
----

Kotlin (Jackson 3.x)::
+
[source,kotlin]
----
public class LazyvalJacksonModule : SimpleModule() {
  override fun setupModule(context: JacksonModule.SetupContext) {
    super.setupModule(context)
    val sers = SimpleSerializers()
    val desers = SimpleDeserializers()
    sers.addSerializer(OrderDate::class.java, orderDateSerializer)
    sers.addSerializer(Quantity::class.java, quantitySerializer)
    desers.addDeserializer(OrderDate::class.java, orderDateDeserializer)
    desers.addDeserializer(Quantity::class.java, quantityDeserializer)
    context.addSerializers(sers)
    context.addDeserializers(desers)
  }

  public companion object {
    private val eMailSerializer: EMailSerializer = EMailSerializer()
    private val orderDateSerializer: OrderDateSerializer = OrderDateSerializer()
    private val quantitySerializer: QuantitySerializer = QuantitySerializer()
    private val isbnSerializer: IsbnSerializer = IsbnSerializer()
    private val eMailDeserializer: EMailDeserializer = EMailDeserializer()
    private val orderDateDeserializer: OrderDateDeserializer = OrderDateDeserializer()
    private val quantityDeserializer: QuantityDeserializer = QuantityDeserializer()
    private val isbnDeserializer: IsbnDeserializer = IsbnDeserializer()
  }

  private class OrderDateSerializer : StdSerializer<OrderDate>(OrderDate::class.java) {
    override fun serialize(
      `value`: OrderDate,
      gen: JsonGenerator,
      ctx: SerializationContext,
    ) {
      val ser = ctx.findValueSerializer(LocalDate::class.java)
      ser.serialize(value.value, gen, ctx)
    }
  }

  private class QuantitySerializer : StdSerializer<Quantity>(Quantity::class.java) {
    override fun serialize(
      `value`: Quantity,
      gen: JsonGenerator,
      ctx: SerializationContext,
    ) {
      gen.writeNumber(value.value)
    }
  }

  private class OrderDateDeserializer : StdDeserializer<OrderDate>(OrderDate::class.java) {
    override fun deserialize(p: JsonParser, ctx: DeserializationContext): OrderDate? {
      val deser = ctx.findContextualValueDeserializer(ctx.constructType(LocalDate::class.java), null)
      val value = deser.deserialize(p, ctx) as LocalDate
      return OrderDate(value)
    }
  }

  private class QuantityDeserializer : StdDeserializer<Quantity>(Quantity::class.java) {
    override fun deserialize(p: JsonParser, ctx: DeserializationContext): Quantity? {
      val value = p.valueAsInt
      return Quantity(value)
    }
  }
}
----
====

The module is registered via ServiceLoader `META-INF\services\com.fasterxml.jackson.databind.Module` (Jackson 2.x) or
`META-INF\services\tools.jackson.databind.JacksonModule` (Jackson 3.x)  which is written to the compiler output
folder. This way other frameworks like RestAssured will also pick it up.

== Quarkus

In case Quarkus is detected, the module will be registed as `ObjectMapperCustomizer` and `@Singleton` bean.
See https://quarkus.io/guides/rest-json#json[Quarkus docs] for details.

[source,java]
----
@Singleton
public class LazyvalJacksonModule extends SimpleModule implements ObjectMapperCustomizer {

  @Override
  public void customize(ObjectMapper objectMapper) {
    objectMapper.registerModule(this);
  }

  // ...
}
----