<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qualityminds.lazyval</groupId>
    <artifactId>lazyval-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Lazyval Project POM</name>
    <description>Parent POM for Lazyval project</description>
    <url>https://github.com/qualityminds/lazyval</url>

    <scm>
        <developerConnection>scm:git:https://github.com/qualityminds/lazyval.git</developerConnection>
    </scm>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <modules>
        <module>core</module>
        <module>utils</module>
        <module>processor</module>
        <module>ksp</module>
        <module>testkit</module>
        <module>integration-test</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <version.java>17</version.java>
        <!-- dependencies -->
        <version.eclipse-collections>13.0.0</version.eclipse-collections>
        <version.groovy>5.0.4</version.groovy>
        <version.javapoet>0.10.0</version.javapoet>
        <version.jetbrains-annotations>26.0.2-1</version.jetbrains-annotations>
        <version.jspecify>1.0.0</version.jspecify>
        <version.kotest>6.0.3</version.kotest>
        <version.kotlin>2.3.0</version.kotlin>
        <version.kotlinpoet>2.2.0</version.kotlinpoet>
        <version.ksp>2.3.4</version.ksp>
        <version.slf4j>2.0.17</version.slf4j>
        <version.spock>2.4-groovy-5.0</version.spock>
        <!-- plugins -->
        <version.plugin.antrun>3.2.0</version.plugin.antrun>
        <version.plugin.build-helper>3.6.1</version.plugin.build-helper>
        <version.plugin.compiler>3.14.1</version.plugin.compiler>
        <version.plugin.dokka>2.1.0</version.plugin.dokka>
        <version.plugin.exec>3.6.3</version.plugin.exec>
        <version.plugin.failsafe>3.5.4</version.plugin.failsafe>
        <version.plugin.flatten>1.7.3</version.plugin.flatten>
        <version.plugin.gmavenplus>4.2.1</version.plugin.gmavenplus>
        <version.plugin.gpg>3.2.8</version.plugin.gpg>
        <version.plugin.jar>3.5.0</version.plugin.jar>
        <version.plugin.javadoc>3.12.0</version.plugin.javadoc>
        <version.plugin.license>2.7.1</version.plugin.license>
        <version.plugin.publish>0.10.0</version.plugin.publish>
        <version.plugin.release>3.3.1</version.plugin.release>
        <version.plugin.shade>3.6.1</version.plugin.shade>
        <version.plugin.source>3.4.0</version.plugin.source>
        <version.plugin.surefire>3.5.4</version.plugin.surefire>
        <version.plugin.templating>3.1.0</version.plugin.templating>
        <version.plugin.ksp2-3rd-party>0.2.0</version.plugin.ksp2-3rd-party>
        <!-- static analysis -->
        <version.checks.error-prone>2.46.0</version.checks.error-prone>
        <version.checks.error-prone.nullaway>0.13.1</version.checks.error-prone.nullaway>
        <version.checks.detekt>2.0.0-alpha.2</version.checks.detekt>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.groovy</groupId>
                <artifactId>groovy-bom</artifactId>
                <version>${version.groovy}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.spockframework</groupId>
                <artifactId>spock-bom</artifactId>
                <version>${version.spock}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${version.slf4j}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${version.slf4j}</version>
            </dependency>
            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>${version.jspecify}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${version.plugin.compiler}</version>
                    <configuration>
                        <release>${version.java}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <version>${version.kotlin}</version>
                    <configuration>
                        <jvmTarget>${version.java}</jvmTarget>
                    </configuration>
                    <executions>
                        <execution>
                            <id>compile</id>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.jetbrains.dokka</groupId>
                    <artifactId>dokka-maven-plugin</artifactId>
                    <version>${version.plugin.dokka}</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <!--
                                    The javadocJar goal uses KotlinAsJava Dokka plugin, which is still experimental and
                                    translates Kotlin signatures to Java signatures.
                                    This is required to package a `-javadoc.jar` artifact, which is a requirement
                                    to publish on Maven Central.
                                -->
                                <goal>javadocJar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.gmavenplus</groupId>
                    <artifactId>gmavenplus-plugin</artifactId>
                    <version>${version.plugin.gmavenplus}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>compileTests</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <targetBytecode>${version.java}</targetBytecode>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.plugin.surefire}</version>
                    <configuration>
                        <includes>
                            <include>**/*Spec</include>
                            <include>**/*Test</include>
                        </includes>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${version.plugin.failsafe}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>${version.plugin.license}</version>
                    <configuration>
                        <includeTransitiveDependencies>true</includeTransitiveDependencies>
                        <excludedScopes>test</excludedScopes>
                    </configuration>
                    <executions>
                        <execution>
                            <id>add-third-party</id>
                            <goals>
                                <goal>add-third-party</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>${project.build.outputDirectory}/META-INF</outputDirectory>
                                <licenseMerges>
                                    <licenseMerge>Apache-2.0|The Apache License, Version 2.0|The Apache Software License, Version 2.0|Apache License, Version 2.0|Apache Public License 2.0</licenseMerge>
                                    <licenseMerge>EPL-2.0|Eclipse Public License 2.0|Eclipse Public License - v 2.0|Eclipse Public License v2.0|EPL 2.0</licenseMerge>
                                    <licenseMerge>EPL-1.0|Eclipse Public License 1.0|Eclipse Public License - v 1.0|Eclipse Public License v1.0|EPL 1.0</licenseMerge>
                                    <licenseMerge>EDL-1.0|Eclipse Distribution License 1.0|Eclipse Distribution License - v 1.0|Eclipse Distribution License v. 1.0|EDL 1.0</licenseMerge>
                                    <licenseMerge>MIT|The MIT License|MIT License|MIT license|The MIT License (MIT)|MIT-style license</licenseMerge>
                                </licenseMerges>
                            </configuration>
                        </execution>
                        <execution>
                            <id>update-project-license</id>
                            <goals>
                                <goal>update-project-license</goal>
                            </goals>
                            <configuration>
                                <licenseName>apache_v2</licenseName>
                                <licenseFile>${project.build.outputDirectory}/META-INF/LICENSE</licenseFile>
                                <organizationName>QualityMinds GmbH</organizationName>
                                <inceptionYear>2025</inceptionYear>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${version.plugin.jar}</version>
                    <configuration>
                        <!-- for some reason the license-plugin is generating the files twice, we only want to keep
                        the ones in META-INF -->
                        <excludes>
                            <exclude>THIRD-PARTY.txt</exclude>
                            <exclude>LICENSE</exclude>
                        </excludes>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>${version.plugin.flatten}</version>
                    <configuration>
                        <flattenMode>oss</flattenMode>
                        <!-- needed to interop with shade-plugin -->
                        <updatePomFile>true</updatePomFile>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>prepare-package</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>static-analysis</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <compilerArgs>
                                <arg>-XDcompilePolicy=simple</arg>
                                <arg>--should-stop=ifError=FLOW</arg>
                                <arg>-Xplugin:ErrorProne -XepOpt:NullAway:AnnotatedPackages=de.qualityminds.lazyval -XepOpt:NullAway:JSpecifyMode=true</arg>
                            </compilerArgs>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>com.google.errorprone</groupId>
                                    <artifactId>error_prone_core</artifactId>
                                    <version>${version.checks.error-prone}</version>
                                </path>
                                <path>
                                    <groupId>com.uber.nullaway</groupId>
                                    <artifactId>nullaway</artifactId>
                                    <version>${version.checks.error-prone.nullaway}</version>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>publish</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${version.plugin.source}</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${version.plugin.javadoc}</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${version.plugin.gpg}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${version.plugin.publish}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                            <autoPublish>true</autoPublish>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-release-plugin</artifactId>
                        <version>${version.plugin.release}</version>
                        <configuration>
                            <autoVersionSubmodules>true</autoVersionSubmodules>
                            <releaseProfiles>publish</releaseProfiles>
                            <tagNameFormat>@{project.version}</tagNameFormat>
                            <goals>deploy</goals>
                            <completionGoals>exec:exec@update-ci-version</completionGoals>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${version.plugin.exec}</version>
                        <executions>
                            <execution>
                                <id>update-ci-version</id>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${project.basedir}/update-lazyval-version.sh</executable>
                                    <arguments>
                                        <argument>${project.version}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <developers>
        <developer>
            <name>Marc Schlegel</name>
            <email>marc.schlegel@qualityminds.de</email>
            <organization>QualityMinds</organization>
            <organizationUrl>http://www.qualityminds.com</organizationUrl>
        </developer>
    </developers>
</project>