// Since Github does not support inlcudes, we use Asciidoc-Reducer with a Github Action
// to generate the actual README as a single file with all includes resolved.
= Kotlin Support via KSP

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

For Kotlin, the original Java Annotation Processor was migrated to KSP2 (Kotlin Symbol Processing) to make use of
the `@LazyValue` annotation on Kotlin classes and data-classes.
This documentation only deals with Kotlin specifics. For motivation, license, legal notices see the main README.

NOTE: KSP2 only officially supports Gradle. Mill has its own KSP2 support. Maven users can currently not make use of KSP2.

== Usage

Add the `@LazyValue` annotation to your (date-)class and the processor will figure out the rest.

.Quantity Dataclass
[source, kotlin]
----
@LazyValue
data class Quantity(val value: Int){
    init {
        require(value > 0) { "Quantity must be greater than 0" }
    }
}
----

.ISBN Object with factory method
[source,kotlin]
----
@LazyValue
class Isbn private constructor(val value: String) {

    init {
        require(value != null) { "Value cannot be null" }
    }

    companion object {
        // will be used by the annotation processor (factory methods have higher precedence)
        @JvmStatic
        @Throws(IllegalArgumentException::class)
        fun parse(value: String): Isbn {
            requireNotNull(value) { "ISBN cannot be null" }

            val cleanValue = value.replace(Regex("[-\\s]"), "")

            when (cleanValue.length) {
                10 -> validateIsbn10(cleanValue)
                13 -> validateIsbn13(cleanValue)
                else -> throw IllegalArgumentException("Invalid ISBN length. Must be 10 or 13 digits (excluding hyphens)")
            }

            return Isbn(value)
        }

        // ... validation, equals, hashCode, toString
----

IMPORTANT: The generated Mapstruct interface will still be a Java file because Mapstruct
is a Java Annotation Processor that cannot read Kotlin sources.

.Generated Mapper definition
[source,java]
----
@Mapper(
    unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface LazyvalMapper {
  default String mapIsbnToWrappedType(Isbn type) {
    if (type == null) {
      return null;
    }
    return type.value();
  }

  default Isbn mapIsbn(String value) {
    if (value == null) {
      return null;
    }
    return Isbn.parse(value);
  }

  default int mapQuantityToWrappedType(Quantity type) {
    return type.getValue();
  }

  default Quantity mapQuantity(int value) {
    return new Quantity(value);
  }
}
----


.Generated JPA AttributeConverter definition
[source, kotlin]
----
@Converter(autoApply = true)
public class IsbnAttributeConverter :  AttributeConverter<Isbn?, String?> {
  override fun convertToDatabaseColumn(type: Isbn?): String? = type?.value()

  override fun convertToEntityAttribute(dbValue: String?): Isbn? = dbValue?.let { Isbn.parse(dbValue) }
}

@Converter(autoApply = true)
public class QuantityAttributeConverter : AttributeConverter<Quantity?, Int?> {
  override fun convertToDatabaseColumn(type: Quantity?): Int? = type?.value

  override fun convertToEntityAttribute(dbValue: Int?): Quantity? = dbValue?.let { Quantity(dbValue) }
}
----

== Setup & Configuration

To use Lazyval, you have to have the annotation on your compilepath and the annotation-processor
enabled during compilation.

NOTE: The `@Lazyval` annotation is erased during compile time, so there is no need
that consumers need a transitive dependency to the module.

=== Gradle

[source, kotlin]
----
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.2.20")
    compileOnly("de.qualityminds.lazyval:lazyval:0.1.0-SNAPSHOT")
    implementation("org.mapstruct:mapstruct:1.6.3")
    compileOnly("jakarta.platform:jakarta.jakartaee-api:11.0.0")

    ksp("de.qualityminds.lazyval:lazyval-ksp:0.1.0-SNAPSHOT")
    annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")
}

ksp {
    arg("lazyval.jpa.generatedPackage", "test.boundary.persistence")
    arg("lazyval.mapstruct.generatedPackage", "test")
}
----

Make sure to enable KSP2 mode in `gradle.properties`

[source, properties]
----
ksp.useKSP2=true
----

=== Mill

Add the `KspModule` and configure accordingly

[source, scala]
----
//| mill-version: 1.0.5
//| mill-jvm-version: zulu:21
import coursier.LocalRepositories.Dangerous
import coursier.Repositories
import mill.*
import mill.kotlinlib.*
import mill.kotlinlib.ksp.*

object `package` extends KotlinMavenModule with KspModule {

  object Version{
    val lazyval = "0.1.0-SNAPSHOT"
    val mapstruct = "1.6.3"
    val jpa = "3.2.0"
  }

  override def kotlinVersion = "2.2.20"
  override def kspVersion = "2.0.3"
  override def kspJvmTarget = "21"
  override def kspModuleMode = KspModuleMode.Ksp2 // could be ommited, as it is the default


  override def mvnDeps: T[Seq[Dep]] = Seq(
    mvn"org.mapstruct:mapstruct:${Version.mapstruct}"
  )

  override def compileMvnDeps: T[Seq[Dep]] = Seq(
    mvn"de.qualityminds.lazyval:lazyval:${Version.lazyval}",
    mvn"jakarta.persistence:jakarta.persistence-api:${Version.jpa}",
    mvn"org.mapstruct:mapstruct-processor:${Version.mapstruct}"
  )

  override def kotlinSymbolProcessors: T[Seq[Dep]] = Seq(
    mvn"de.qualityminds.lazyval:lazyval-ksp:${Version.lazyval}"
  )

  def javacOptions = super.javacOptions() ++ Seq(
    // as of Java 25, Annotation Processors must be explicitly enabled
    // alternatively use "-proc:full"
    "-processor", "org.mapstruct.ap.MappingProcessor",
    "-Amapstruct.unmappedTargetPolicy=ERROR",
  )

  override def kspProcessorOptions: T[Map[String, String]] = Map(
    "lazyval.jpa.generatedPackage" -> "test.boundary.persistence",
    "lazyval.mapstruct.generatedPackage" -> "test"
  )
}
----
