<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.qualityminds.lazyval</groupId>
        <artifactId>lazyval-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>lazyval-ksp</artifactId>
    <name>Lazyval Kotlin-Symbol-Processor</name>
    <description>KSP2 implementation of the Lazyval annotation processing</description>

    <properties>
        <version.kotlin>2.2.20</version.kotlin>
        <version.ksp>2.0.4</version.ksp>
        <version.kotlinpoet>2.2.0</version.kotlinpoet>
        <version.javapoet>0.7.0</version.javapoet>
        <version.kotest>6.0.3</version.kotest>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.qualityminds.lazyval</groupId>
            <artifactId>lazyval</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.devtools.ksp</groupId>
            <artifactId>symbol-processing-api</artifactId>
            <version>${version.kotlin}-${version.ksp}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>kotlinpoet-ksp</artifactId>
            <version>${version.kotlinpoet}</version>
        </dependency>
        <dependency>
            <groupId>com.palantir.javapoet</groupId>
            <artifactId>javapoet</artifactId>
            <version>${version.javapoet}</version>
        </dependency>
        <!-- Tests -->
        <dependency>
            <groupId>de.qualityminds.lazyval</groupId>
            <artifactId>test-utils</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-runner-junit5</artifactId>
            <version>${version.kotest}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.kotest</groupId>
            <artifactId>kotest-assertions-core</artifactId>
            <version>${version.kotest}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk-jvm</artifactId>
            <version>1.14.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- The following Dependencies are used to set up a KSP2 and Kotlin compiler toolchain in the tests -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-compiler-embeddable</artifactId>
            <version>${version.kotlin}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <!-- currently experimental only -->
            <!-- see https://github.com/Kotlin/KEEP/blob/build-tools-api/proposals/extensions/build-tools-api.md -->
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-build-tools-impl</artifactId>
            <version>${version.kotlin}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.devtools.ksp</groupId>
            <artifactId>symbol-processing</artifactId>
            <version>${version.kotlin}-${version.ksp}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.devtools.ksp</groupId>
            <artifactId>symbol-processing-common-deps</artifactId>
            <version>${version.kotlin}-${version.ksp}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <!-- see https://github.com/google/ksp/blob/fd792aff8eb155f300a80b70855c862388331284/docs/ksp2entrypoints.md -->
            <groupId>com.google.devtools.ksp</groupId>
            <artifactId>symbol-processing-aa-embeddable</artifactId>
            <version>${version.kotlin}-${version.ksp}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <artifactId>kotlin-maven-plugin</artifactId>
                <groupId>org.jetbrains.kotlin</groupId>
                <version>${version.kotlin}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>