<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.acme</groupId>
        <artifactId>lazyval-spi-sample-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>custom-lazyval-generator</artifactId>

    <name>Java SPI Sample - SPI Implementation</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>6.0.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.qualityminds.lazyval</groupId>
            <artifactId>lazyval-processor</artifactId>
            <version>${version.lazyval}</version>
        </dependency>
        <dependency>
            <groupId>com.qualityminds.lazyval</groupId>
            <artifactId>lazyval-testkit</artifactId>
            <version>${version.lazyval}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <!-- to see logs during test-execution, provide any SLF4J impl -->
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.17</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <!--
                    Disable annotation processing - this module provides SPI, doesn't use it.
                    Alternatively, use Google AutoService.
                    -->
                    <proc>none</proc>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>