spring.application.name=spring-app
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=spring
spring.cassandra.schema-action=create-if-not-exists

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=lazyval
spring.mongodb.representation.uuid=standard
