<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.qualityminds.lazyval.example</groupId>
    <artifactId>example-maven</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <name>Lazyval Sample Kotlin</name>

    <!-- tag::docu[] -->
    <properties>
        <!-- tag::excluded[] -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- end::excluded[] -->
        <version.kotlin>2.3.0</version.kotlin>
        <version.lazyval>0.3.1</version.lazyval>
        <version.mapstruct>1.6.3</version.mapstruct>
        <version.jakarta-ee>11.0.0</version.jakarta-ee>
        <version.jackson>3.1.0</version.jackson>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.qualityminds.lazyval</groupId>
            <artifactId>lazyval</artifactId>
            <version>${version.lazyval}</version>
            <optional>true</optional> <!--1-->
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${version.kotlin}</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${version.mapstruct}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${version.jakarta-ee}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${version.jackson}</version>
        </dependency>
    </dependencies>
    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <plugins>
            <!-- tag::excluded[] -->
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${version.kotlin}</version>
                <configuration>
                    <jvmTarget>17</jvmTarget>
                </configuration>
                <executions>
                    <!-- see https://kotlinlang.org/docs/maven-compile-package.html for mixed Java & Kotlin -->
                    <execution>
                        <id>kotlin-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <!-- Ensure Kotlin code can reference Java code -->
                                <sourceDir>src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- end::excluded[] -->
            <plugin>
                <groupId>me.kpavlov.ksp.maven</groupId>
                <artifactId>ksp-maven-plugin</artifactId>
                <version>0.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.qualityminds.lazyval</groupId>
                        <artifactId>lazyval-ksp</artifactId>
                        <version>${version.lazyval}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <apOptions>
                        <lazyval.generators.basePackage>
                            test
                        </lazyval.generators.basePackage>
                        <lazyval.mapstruct.package>
                            test.custom
                        </lazyval.mapstruct.package>
                    </apOptions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>17</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${version.mapstruct}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amapstruct.unmappedTargetPolicy=ERROR</arg>
                    </compilerArgs>
                </configuration>
                <executions>
                    <!-- see https://kotlinlang.org/docs/maven-compile-package.html for mixed Java & Kotlin -->
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>java-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>java-test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <!-- end::docu[] -->
</project>
