package test.boundary.persistence;

import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import java.util.List;
import javax.annotation.processing.Generated;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;
import org.springframework.data.convert.ReadingConverter;
import org.springframework.data.convert.WritingConverter;
import org.springframework.data.mongodb.core.convert.MongoCustomConversions;
import scenarios.java.Ids;
import scenarios.java.Isbn;
import scenarios.java.OrderDate;
import scenarios.java.Quantity;

/**
 * Generated Spring Data converter configuration.
 * <p>
 * Registers all read/write converters for types annotated with {@code @Lazyval}
 * with the appropriate Spring Data store-specific conversion service.
 * <p>
 * Generated by the Lazyval annotation processor. Do not modify.
 */
@Generated("com.qualityminds.lazyval.processor.internal.codegen.springdata.SpringDataGenerator")
@Configuration
public class LazyvalSpringDataConfiguration {
  @Bean
  public MongoCustomConversions mongoCustomConversions() {
    List<Converter<?, ?>> converters = List.of(
            new IdsProductIdReadConverter(),
            new IdsProductIdWriteConverter(),
            new IsbnReadConverter(),
            new IsbnWriteConverter(),
            new OrderDateReadConverter(),
            new OrderDateWriteConverter(),
            new QuantityReadConverter(),
            new QuantityWriteConverter()
        );
    return new MongoCustomConversions(converters);
  }

  @ReadingConverter
  private static final class IdsProductIdReadConverter implements Converter<String, Ids.ProductId> {
    @Override
    public Ids.ProductId convert(String source) {
      return Ids.ProductId.of(source);
    }
  }

  @WritingConverter
  private static final class IdsProductIdWriteConverter implements Converter<Ids.ProductId, String> {
    @Override
    public String convert(Ids.ProductId source) {
      return source.value();
    }
  }

  @ReadingConverter
  private static final class IsbnReadConverter implements Converter<String, Isbn> {
    @Override
    public Isbn convert(String source) {
      return Isbn.parse(source);
    }
  }

  @WritingConverter
  private static final class IsbnWriteConverter implements Converter<Isbn, String> {
    @Override
    public String convert(Isbn source) {
      return source.getValue();
    }
  }

  @ReadingConverter
  private static final class OrderDateReadConverter implements Converter<LocalDate, OrderDate> {
    @Override
    public OrderDate convert(LocalDate source) {
      return new OrderDate(source);
    }
  }

  @WritingConverter
  private static final class OrderDateWriteConverter implements Converter<OrderDate, LocalDate> {
    @Override
    public LocalDate convert(OrderDate source) {
      return source.value();
    }
  }

  @ReadingConverter
  private static final class QuantityReadConverter implements Converter<Integer, Quantity> {
    @Override
    public Quantity convert(Integer source) {
      return new Quantity(source);
    }
  }

  @WritingConverter
  private static final class QuantityWriteConverter implements Converter<Quantity, Integer> {
    @Override
    public Integer convert(Quantity source) {
      return source.value();
    }
  }
}
