package test.boundary.persistence

import jakarta.`annotation`.Generated
import java.time.LocalDate
import kotlin.Int
import kotlin.String
import org.springframework.`data`.cassandra.core.convert.CassandraCustomConversions
import org.springframework.`data`.convert.ReadingConverter
import org.springframework.`data`.convert.WritingConverter
import org.springframework.context.`annotation`.Bean
import org.springframework.context.`annotation`.Configuration
import org.springframework.core.convert.converter.Converter
import scenarios.kotlin.Ids
import scenarios.kotlin.Isbn
import scenarios.kotlin.NullableQuantity
import scenarios.kotlin.OrderDate
import scenarios.kotlin.Quantity

/**
 * Generated Spring Data converter configuration.
 *
 * Registers all read/write converters for types annotated with `@Lazyval`
 * with the appropriate Spring Data store-specific conversion service.
 *
 * Generated by the Lazyval annotation processor. Do not modify.
 */
@Generated("com.qualityminds.lazyval.ksp.internal.codegen.springdata.SpringDataGenerator")
@Configuration
public class LazyvalSpringDataConfiguration {
  @Bean
  public fun cassandraCustomConversions(): CassandraCustomConversions {
    val converters = listOf(
            IdsProductIdReadConverter(),
            IdsProductIdWriteConverter(),
            IsbnReadConverter(),
            IsbnWriteConverter(),
            NullableQuantityReadConverter(),
            NullableQuantityWriteConverter(),
            OrderDateReadConverter(),
            OrderDateWriteConverter(),
            QuantityReadConverter(),
            QuantityWriteConverter()
        )
    return CassandraCustomConversions(converters)
  }
}

@ReadingConverter
private class IdsProductIdReadConverter : Converter<String, Ids.ProductId> {
  override fun convert(source: String): Ids.ProductId = Ids.ProductId.of(source)
}

@WritingConverter
private class IdsProductIdWriteConverter : Converter<Ids.ProductId, String> {
  override fun convert(source: Ids.ProductId): String = source.value
}

@ReadingConverter
private class IsbnReadConverter : Converter<String, Isbn> {
  override fun convert(source: String): Isbn = Isbn.parse(source)
}

@WritingConverter
private class IsbnWriteConverter : Converter<Isbn, String> {
  override fun convert(source: Isbn): String = source.value
}

@ReadingConverter
private class NullableQuantityReadConverter : Converter<Int, NullableQuantity?> {
  override fun convert(source: Int): NullableQuantity? = NullableQuantity.ofNullable(source)
}

@WritingConverter
private class NullableQuantityWriteConverter : Converter<NullableQuantity, Int> {
  override fun convert(source: NullableQuantity): Int = source.value
}

@ReadingConverter
private class OrderDateReadConverter : Converter<LocalDate, OrderDate> {
  override fun convert(source: LocalDate): OrderDate = OrderDate(source)
}

@WritingConverter
private class OrderDateWriteConverter : Converter<OrderDate, LocalDate> {
  override fun convert(source: OrderDate): LocalDate = source.date
}

@ReadingConverter
private class QuantityReadConverter : Converter<Int, Quantity> {
  override fun convert(source: Int): Quantity = Quantity(source)
}

@WritingConverter
private class QuantityWriteConverter : Converter<Quantity, Int> {
  override fun convert(source: Quantity): Int = source.value
}
