package com.qualityminds.lazyval.testkit;

import org.eclipse.collections.api.factory.Lists;
import org.eclipse.collections.api.list.ImmutableList;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import static org.eclipse.collections.impl.collector.Collectors2.toImmutableList;

/**
 * ADT for test results, distinguishing between Java and Kotlin
 */
public sealed interface Testresult {

    /**
     * Test result ADT specific to Lazyvals Java annotation processor.
     * <p>
     * Use this to set up the expected result for a test case.
     */
    sealed interface Java extends Testresult {

        /**
         * Compilation was a success, without any warnings.
         * @param generatedFiles list of expected generated files (order does not matter)
         */
        record Success(ImmutableList<String> generatedFiles) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public Success {
                Objects.requireNonNull(generatedFiles);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
            }

            /**
             * Convenience constructor for better interop with Groovy list literals
             * @param generatedFiles list of expected generated files
             */
            public Success(List<String> generatedFiles) {
                this(Lists.immutable.ofAll(generatedFiles));
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Success(String... generatedFiles) {
                this(Lists.immutable.ofAll(Arrays.asList(generatedFiles)));
            }
        }

        /**
         * Compilation was a success, but warnings were generated.
         * @param generatedFiles list of expected generated files (order does not matter)
         * @param warnings list of expected warnings
         */
        record SuccessWithWarnings(ImmutableList<String> generatedFiles,
                                   ImmutableList<String> warnings) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public SuccessWithWarnings {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
                if(warnings.isEmpty()){
                    throw new IllegalArgumentException("Warnings must not be empty");
                }
            }
        }

        /**
         * Compilation was a success, but nothing was generated by the processor.
         * This is the case when, for instance, none of the classpath-requirements for any generator have been met,
         * or when no generator was active.
         */
        record NothingGenerated() implements Java {
        }

        /**
         * Compilation failed with errors. Usually you don't want to expect this in a test,
         * but the testkit will return this
         * @param errors list of errors
         */
        record Failure(ImmutableList<String> errors) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public Failure {
                Objects.requireNonNull(errors);
                errors = errors.toSortedList().toImmutable();
                if(errors.isEmpty()){
                    throw new IllegalArgumentException("Errors must not be empty");
                }
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Failure(String error) {
                this(Lists.immutable.of(error));
            }
        }

        /**
         * Compilation succeeded, every requested {@link Approval} matched, <em>and</em> no
         * additional files were generated beyond those covered by the approvals. {@code Approved} is a
         * strict closed-set verdict: a run that produces files outside the approved set yields
         * {@link ApprovalMismatch} carrying one {@link ApprovalMismatch.Failure.UnexpectedFile}
         * per surplus file, not {@code Approved}.
         * <p>
         * Returned by the testkit only when one or more {@code ApprovalDefinition}s were passed to
         * {@link Testkit#run(java.nio.file.Path, com.qualityminds.lazyval.testkit.scenarios.Scenario, Approval...)}.
         *
         * @param generatedFiles relative paths of every file produced; in an {@code Approved} result
         *                       this is exactly the set of {@link Approval#generatedPath()}s
         *                       that were passed in
         * @param warnings warnings observed during the run; default empty, but assert non-empty if a
         *                 specific warning is expected
         */
        record Approved(ImmutableList<String> generatedFiles,
                        ImmutableList<String> warnings) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public Approved {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
            }

            /**
             * Builds the expected {@code Approved} from the same {@link Approval}s passed to
             * {@code Testkit.run(...)}. The generated-files list is derived directly from the definitions'
             * {@link Approval#generatedPath() generatedPath}s — no duplication needed at the call site.
             *
             * @param approvals the approval definitions used in the run
             * @return an {@code Approved} expectation with no warnings; chain {@link #withWarnings(String...)}
             *         when a specific warning is expected
             */
            public static Approved of(Approval... approvals) {
                var paths = Arrays.stream(approvals)
                        .map(Approval::generatedPath)
                        .collect(toImmutableList());
                return new Approved(paths, Lists.immutable.empty());
            }

            public static Approved of(Collection<Approval> approvals) {
                return of(approvals.toArray(Approval[]::new));
            }

            /**
             * Returns a copy of this expectation that also requires the given warnings. Repeating any
             * existing warnings is fine; the underlying list is sorted and deduplicated by equality.
             *
             * @param warnings warnings expected to be observed during the run
             * @return a new {@code Approved} expectation with the warnings attached
             */
            public Approved withWarnings(String... warnings) {
                return new Approved(generatedFiles, Lists.immutable.of(warnings));
            }
        }

        /**
         * Compilation succeeded but the strict-closed-set contract of {@link Approved} was not
         * satisfied: at least one approval differed from the generated content
         * ({@link Failure.ContentDiffers}), targeted a path that was not generated
         * ({@link Failure.FileNotFound}), or the run produced a file no approval was declared for
         * ({@link Failure.UnexpectedFile}).
         * <p>
         * {@link #toString()} prints a per-failure description so the assertion error in the test
         * runner is immediately useful, including the rendered diff for content failures.
         *
         * @param failures one entry per individual failure (a single run may produce several)
         */
        record ApprovalMismatch(ImmutableList<Failure> failures) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public ApprovalMismatch {
                Objects.requireNonNull(failures);
                if (failures.isEmpty()) {
                    throw new IllegalArgumentException("ApprovalMismatch requires at least one failure");
                }
            }

            /** A single reason the strict approval contract was not satisfied. */
            public sealed interface Failure {
                /**
                 * The file existed at the expected path but its content differed.
                 *
                 * @param generatedPath the path the approval targeted (relative to the source-output root)
                 * @param renderedDiff the rendered, plain-text diff between actual and expected content,
                 *                     already including a few lines of context around each change
                 */
                record ContentDiffers(String generatedPath, String renderedDiff) implements Failure {}

                /**
                 * No file was generated at the expected path. The list of paths the run actually produced
                 * is included to make the diagnostic message immediately actionable (e.g. spotting a
                 * package-override mistake).
                 *
                 * @param expectedPath the path the approval targeted
                 * @param actualGeneratedPaths every file the run produced, for cross-reference
                 */
                record FileNotFound(String expectedPath,
                                    ImmutableList<String> actualGeneratedPaths) implements Failure {}

                /**
                 * The run generated a file that no {@link Approval} covers. {@link Approved}
                 * is a closed set; surplus files surface here rather than passing silently.
                 *
                 * @param generatedPath the surplus file's path (relative to the source-output root)
                 */
                record UnexpectedFile(String generatedPath) implements Failure {}
            }

            @Override
            public String toString() {
                return failures.stream()
                        .map(ApprovalMismatch::renderFailure)
                        .collect(Collectors.joining(System.lineSeparator() + System.lineSeparator()));
            }

            private static String renderFailure(Failure failure) {
                if (failure instanceof Failure.ContentDiffers cd) {
                    return cd.generatedPath() + ":" + System.lineSeparator() + cd.renderedDiff();
                }
                if (failure instanceof Failure.FileNotFound fnf) {
                    return "expected " + fnf.expectedPath() + " but the run produced " + fnf.actualGeneratedPaths();
                }
                if (failure instanceof Failure.UnexpectedFile uf) {
                    return "unexpected file generated (no approval declared): " + uf.generatedPath();
                }
                throw new IllegalStateException("Unknown failure type: " + failure);
            }
        }
    }

    /**
     * Test result ADT specific to Lazyvals Kotlin KSP2 processor.
     * <p>
     * Use this to set up the expected result for a test case.
     */
    sealed interface Kotlin extends Testresult {
        /**
         * Compilation was a success, without any warnings.
         * @param generatedFiles list of expected generated files (order does not matter)
         */
        record Success(ImmutableList<String> generatedFiles) implements Kotlin {

            @SuppressWarnings("doclint:accessibility,missing")
            public Success {
                Objects.requireNonNull(generatedFiles);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
            }

            /**
             * Convenience constructor for better interop with Groovy list literals
             * @param generatedFiles list of expected generated files
             */
            public Success(List<String> generatedFiles) {
                this(Lists.immutable.ofAll(generatedFiles));
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Success(String... generatedFiles) {
                this(Lists.immutable.ofAll(Arrays.asList(generatedFiles)));
            }
        }

        /**
         * Compilation was a success, but warnings were generated.
         * @param generatedFiles list of expected generated files (order does not matter)
         * @param warnings list of expected warnings
         */
        record SuccessWithWarnings(ImmutableList<String> generatedFiles,
                                   ImmutableList<String> warnings) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public SuccessWithWarnings {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
                if(warnings.isEmpty()){
                    throw new IllegalArgumentException("Warnings must not be empty");
                }
            }
        }

        /**
         * Compilation was a success, but nothing was generated by the processor.
         * This is the case when, for instance, none of the classpath-requirements for any generator have been met,
         * or when no generator was active.
         */
        record NothingGenerated() implements Kotlin {
        }

        /**
         * Compilation failed with errors. Usually you don't want to expect this in a test,
         * but the testkit will return this in case of errors.
         * @param errors list of errors
         */
        record Failure(ImmutableList<String> errors) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public Failure {
                Objects.requireNonNull(errors);
                errors = errors.toSortedList().toImmutable();
                if(errors.isEmpty()){
                    throw new IllegalArgumentException("Errors must not be empty");
                }
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Failure(String error) {
                this(Lists.immutable.of(error));
            }
        }

        /** See {@link Java.Approved} — the Kotlin equivalent. */
        record Approved(ImmutableList<String> generatedFiles,
                        ImmutableList<String> warnings) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public Approved {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
            }

            /** See {@link Java.Approved#of(Approval...)}. */
            public static Approved of(Approval... approvals) {
                var paths = Arrays.stream(approvals)
                        .map(Approval::generatedPath)
                        .collect(toImmutableList());
                return new Approved(paths, Lists.immutable.empty());
            }

            public static Kotlin.Approved of(Collection<Approval> approvals) {
                return of(approvals.toArray(Approval[]::new));
            }

            /** See {@link Java.Approved#withWarnings(String...)}. */
            public Approved withWarnings(String... warnings) {
                return new Approved(generatedFiles, Lists.immutable.of(warnings));
            }
        }

        /** See {@link Java.ApprovalMismatch} — the Kotlin equivalent. */
        record ApprovalMismatch(ImmutableList<Failure> failures) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public ApprovalMismatch {
                Objects.requireNonNull(failures);
                if (failures.isEmpty()) {
                    throw new IllegalArgumentException("ApprovalMismatch requires at least one failure");
                }
            }

            /** A single reason the strict approval contract was not satisfied. See {@link Java.ApprovalMismatch.Failure}. */
            public sealed interface Failure {
                record ContentDiffers(String generatedPath, String renderedDiff) implements Failure {}
                record FileNotFound(String expectedPath,
                                    ImmutableList<String> actualGeneratedPaths) implements Failure {}
                record UnexpectedFile(String generatedPath) implements Failure {}
            }

            @Override
            public String toString() {
                return failures.stream()
                        .map(ApprovalMismatch::renderFailure)
                        .collect(Collectors.joining(System.lineSeparator() + System.lineSeparator()));
            }

            private static String renderFailure(Failure failure) {
                if (failure instanceof Failure.ContentDiffers cd) {
                    return cd.generatedPath() + ":" + System.lineSeparator() + cd.renderedDiff();
                }
                if (failure instanceof Failure.FileNotFound fnf) {
                    return "expected " + fnf.expectedPath() + " but the run produced " + fnf.actualGeneratedPaths();
                }
                if (failure instanceof Failure.UnexpectedFile uf) {
                    return "unexpected file generated (no approval declared): " + uf.generatedPath();
                }
                throw new IllegalStateException("Unknown failure type: " + failure);
            }
        }
    }

}
