package com.qualityminds.lazyval.testkit;

import org.eclipse.collections.api.factory.Lists;
import org.eclipse.collections.api.list.ImmutableList;

import java.util.Arrays;
import java.util.List;
import java.util.Objects;

/**
 * ADT for test results, distinguishing between Java and Kotlin
 */
public sealed interface Testresult {

    /**
     * Test result ADT specific to Lazyvals Java annotation processor.
     * <p>
     * Use this to set up the expected result for a test case.
     */
    sealed interface Java extends Testresult {

        /**
         * Compilation was a success, without any warnings.
         * @param generatedFiles list of expected generated files (order does not matter)
         */
        record Success(ImmutableList<String> generatedFiles) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public Success {
                Objects.requireNonNull(generatedFiles);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
            }

            /**
             * Convenience constructor for better interop with Groovy list literals
             * @param generatedFiles list of expected generated files
             */
            public Success(List<String> generatedFiles) {
                this(Lists.immutable.ofAll(generatedFiles));
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Success(String... generatedFiles) {
                this(Lists.immutable.ofAll(Arrays.asList(generatedFiles)));
            }
        }

        /**
         * Compilation was a success, but warnings were generated.
         * @param generatedFiles list of expected generated files (order does not matter)
         * @param warnings list of expected warnings
         */
        record SuccessWithWarnings(ImmutableList<String> generatedFiles,
                                   ImmutableList<String> warnings) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public SuccessWithWarnings {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
                if(warnings.isEmpty()){
                    throw new IllegalArgumentException("Warnings must not be empty");
                }
            }
        }

        /**
         * Compilation was a success, but nothing was generated by the processor.
         * This is the case when, for instance, none of the classpath-requirements for any generator have been met,
         * or when no generator was active.
         */
        record NothingGenerated() implements Java {
        }

        /**
         * Compilation failed with errors. Usually you don't want to expect this in a test,
         * but the testkit will return this
         * @param errors list of errors
         */
        record Failure(ImmutableList<String> errors) implements Java {
            @SuppressWarnings("doclint:accessibility,missing")
            public Failure {
                Objects.requireNonNull(errors);
                errors = errors.toSortedList().toImmutable();
                if(errors.isEmpty()){
                    throw new IllegalArgumentException("Errors must not be empty");
                }
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Failure(String error) {
                this(Lists.immutable.of(error));
            }
        }
    }

    /**
     * Test result ADT specific to Lazyvals Kotlin KSP2 processor.
     * <p>
     * Use this to set up the expected result for a test case.
     */
    sealed interface Kotlin extends Testresult {
        /**
         * Compilation was a success, without any warnings.
         * @param generatedFiles list of expected generated files (order does not matter)
         */
        record Success(ImmutableList<String> generatedFiles) implements Kotlin {

            @SuppressWarnings("doclint:accessibility,missing")
            public Success {
                Objects.requireNonNull(generatedFiles);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Success(String... generatedFiles) {
                this(Lists.immutable.ofAll(Arrays.asList(generatedFiles)));
            }
        }

        /**
         * Compilation was a success, but warnings were generated.
         * @param generatedFiles list of expected generated files (order does not matter)
         * @param warnings list of expected warnings
         */
        record SuccessWithWarnings(ImmutableList<String> generatedFiles,
                                   ImmutableList<String> warnings) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public SuccessWithWarnings {
                Objects.requireNonNull(generatedFiles);
                Objects.requireNonNull(warnings);
                generatedFiles = generatedFiles.toSortedList().toImmutable();
                warnings = warnings.toSortedList().toImmutable();
                if(warnings.isEmpty()){
                    throw new IllegalArgumentException("Warnings must not be empty");
                }
            }
        }

        /**
         * Compilation was a success, but nothing was generated by the processor.
         * This is the case when, for instance, none of the classpath-requirements for any generator have been met,
         * or when no generator was active.
         */
        record NothingGenerated() implements Kotlin {
        }

        /**
         * Compilation failed with errors. Usually you don't want to expect this in a test,
         * but the testkit will return this in case of errors.
         * @param errors list of errors
         */
        record Failure(ImmutableList<String> errors) implements Kotlin {
            @SuppressWarnings("doclint:accessibility,missing")
            public Failure {
                Objects.requireNonNull(errors);
                errors = errors.toSortedList().toImmutable();
                if(errors.isEmpty()){
                    throw new IllegalArgumentException("Errors must not be empty");
                }
            }

            @SuppressWarnings("doclint:accessibility,missing")
            public Failure(String error) {
                this(Lists.immutable.of(error));
            }
        }
    }

}
