package com.qualityminds.lazyval.testkit.internal.toolchain.kotlin;

import com.qualityminds.lazyval.testkit.dependencies.Dependency;
import com.qualityminds.lazyval.testkit.scenarios.Scenario;

import javax.tools.StandardLocation;
import javax.tools.ToolProvider;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Third step in the Kotlin toolchain: compiles Java sources generated by KSP using javac.
 * <p>
 * KSP only produces sources and {@code kotlinc} reads {@code .java} files for symbol resolution
 * but does not compile them to bytecode. Without this step, compile errors in generated Java code
 * (e.g. from Mapstruct) would go unnoticed during testing.
 * <p>
 * Runs after {@link KotlinCompileStep} so the kotlinc bytecode output sits on the classpath.
 * Returns {@link StepOutcome#SKIPPED} when KSP produced no Java sources.
 */
class JavaCompileStep {

    private final ProjectLayout layout;
    private final List<File> classpath;
    private final LogCollector logCollector;

    private JavaCompileStep(ProjectLayout layout, List<File> classpath, LogCollector logCollector) {
        this.layout = layout;
        this.classpath = classpath;
        this.logCollector = logCollector;
    }

    public StepOutcome run() {
        try {
            var generatedJavaDir = layout.kspJavaOutput();
            if (!Files.isDirectory(generatedJavaDir)) {
                return StepOutcome.SKIPPED;
            }
            List<File> javaSources;
            try (var stream = Files.walk(generatedJavaDir)) {
                javaSources = stream
                        .filter(p -> !Files.isDirectory(p))
                        .filter(p -> p.toString().endsWith(".java"))
                        .map(Path::toFile)
                        .toList();
            }
            if (javaSources.isEmpty()) {
                return StepOutcome.SKIPPED;
            }

            var compiler = ToolProvider.getSystemJavaCompiler();
            var diagnostics = new LoggingDiagnosticsCollector(logCollector);
            // try-with-resources releases the file manager's jar handles after the task call;
            // without it the handles linger until GC and on Windows block subsequent file deletes.
            try (var fileManager = compiler.getStandardFileManager(diagnostics, null, null)) {
                // Reuse the same build/classes directory used by kotlinc, both as output and on the classpath,
                // so generated Java can resolve Kotlin types compiled by the previous step.
                var classesDir = Files.createDirectories(layout.classes()).toFile();
                var fullClasspath = new ArrayList<>(classpath);
                fullClasspath.add(classesDir);

                fileManager.setLocation(StandardLocation.CLASS_OUTPUT, List.of(classesDir));
                fileManager.setLocation(StandardLocation.CLASS_PATH, fullClasspath);

                var compilationUnits = fileManager.getJavaFileObjects(javaSources.toArray(File[]::new));
                var task = compiler.getTask(null, fileManager, diagnostics, null, null, compilationUnits);
                task.setProcessors(List.of());
                return task.call() ? StepOutcome.SUCCESS : StepOutcome.COMPILE_ERROR;
            }
        } catch (Exception e) {
            throw new RuntimeException("Java compilation of generated sources failed", e);
        }
    }

    public static JavaCompileStep create(ProjectLayout layout, Scenario.Descriptor scenarioDescriptor, LogCollector logCollector) {
        var classpath = new ArrayList<>(CoreModuleDependency.RESOLVED_FILE.toSet());
        KotlinToolchainDependencies.KOTLIN_STDLIB.resolve().forEach(classpath::add);
        scenarioDescriptor.dependencies().stream().map(Dependency::resolve).forEach(deps -> classpath.addAll(deps.toSet()));
        return new JavaCompileStep(layout, List.copyOf(classpath), logCollector);
    }
}
