package com.qualityminds.lazyval.testkit.internal.toolchain.kotlin;

import com.qualityminds.lazyval.collections.NonEmptySet;
import com.qualityminds.lazyval.testkit.dependencies.Dependency;
import com.qualityminds.lazyval.testkit.scenarios.Scenario;
import org.eclipse.collections.api.factory.Lists;
import org.jetbrains.kotlin.buildtools.api.CompilationService;
import org.jetbrains.kotlin.buildtools.api.CompilerExecutionStrategyConfiguration;
import org.jetbrains.kotlin.buildtools.api.ExperimentalBuildToolsApi;
import org.jetbrains.kotlin.buildtools.api.ProjectId;
import org.jetbrains.kotlin.buildtools.api.jvm.JvmCompilationConfiguration;

import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * Second step in the Kotlin toolchain: compiles the original Kotlin sources plus the {@code .kt} and
 * {@code .java} files generated by {@link KspStep}.
 * <p>
 * The Kotlin compiler reads {@code .java} sources only for symbol resolution (so that referenced Java
 * types resolve), it does <em>not</em> emit bytecode for them. That responsibility falls to
 * {@link JavaCompileStep}, which runs afterward.
 */
@ExperimentalBuildToolsApi
record KotlinCompileStep(ProjectLayout layout, CompilationService service,
                         CompilerExecutionStrategyConfiguration strategyConfig,
                         JvmCompilationConfiguration compilationConfig, List<File> sources,
                         List<File> compilerClasspath) {

    private List<File> findAllSourceFiles(File file) {
        if (file.isDirectory()) {
            var files = file.listFiles();
            if (files == null) {
                return List.of();
            }
            return Stream.of(files)
                    .flatMap(f -> findAllSourceFiles(f).stream())
                    .toList();
        } else {
            var name = file.getName();
            if (name.endsWith(".kt") || name.endsWith(".java")) {
                return List.of(file);
            }
            return List.of();
        }
    }

    public StepOutcome run() {
        try {
            // generated sources don't exist at setup time, so they are discovered here
            var kspJavaSources = findAllSourceFiles(layout.kspJavaOutput().toFile());
            var kspKotlinSources = findAllSourceFiles(layout.kspKotlinOutput().toFile());

            var allSources = new ArrayList<>(sources);
            allSources.addAll(kspJavaSources);
            allSources.addAll(kspKotlinSources);

            // KSP resources (e.g. META-INF/services) are written to a separate directory
            // and need to be on the classpath for ServiceLoader discovery
            var classpathEntries = new ArrayList<>(compilerClasspath);
            var kspResourceDir = layout.kspResourceOutput().toFile();
            if (kspResourceDir.isDirectory()) {
                classpathEntries.add(kspResourceDir);
            }

            var classpathString = classpathEntries.stream()
                    .map(File::getAbsolutePath)
                    .reduce((a, b) -> a + File.pathSeparator + b)
                    .orElse("");

            var arguments = List.of(
                    // destination directory
                    "-d", layout.classes().toAbsolutePath().toString(),
                    // classpath
                    "-classpath", classpathString,
                    // needed to resolve Java types like LocalDate
                    "-jdk-home", System.getProperty("java.home"),
                    // must match what KSP was told; see KotlinToolchain.MODULE_NAME
                    "-module-name", KotlinToolchain.MODULE_NAME,
                    // std-lib and kotlin-reflect will be added to classpath manually
                    // because the kotlin compiler otherwise expects a kotlin-stdlib on the filesystem
                    "-no-stdlib", "-no-reflect"
            );

            var result = service.compileJvm(
                    ProjectId.ProjectUUID.Companion.RandomProjectUUID(),
                    strategyConfig,
                    compilationConfig,
                    allSources,
                    arguments
            );

            return switch (result) {
                case COMPILATION_SUCCESS -> StepOutcome.SUCCESS;
                case COMPILATION_ERROR -> StepOutcome.COMPILE_ERROR;
                case COMPILATION_OOM_ERROR, COMPILER_INTERNAL_ERROR -> StepOutcome.INTERNAL_ERROR;
            };
        } catch (Exception e) {
            throw new RuntimeException("Kotlin compilation failed", e);
        }
    }

    public static KotlinCompileStep create(
            ClassLoader classLoader,
            ProjectLayout layout,
            Scenario.Descriptor scenarioDescriptor, LogCollector logCollector) {
        try {
            var extended = Lists.mutable.<Dependency>empty()
                    // additional dependencies are needed for the Kotlin compiler
                    .with(KotlinToolchainDependencies.KOTLIN_STDLIB)
                    .with(KotlinToolchainDependencies.KOTLIN_REFLECT)
                    .withAll(scenarioDescriptor.dependencies())
                    .toImmutable();


            var compilerClasspath = Stream.concat(extended.stream().map(Dependency::resolve).flatMap(NonEmptySet::stream), CoreModuleDependency.RESOLVED_FILE.stream()).toList();

            var service = CompilationService.loadImplementation(classLoader);
            var strategyConfig = service.makeCompilerExecutionStrategyConfiguration();
            var compilationConfig = service.makeJvmCompilationConfiguration();

            var incrementalConfig = compilationConfig.makeClasspathSnapshotBasedIncrementalCompilationConfiguration();
            incrementalConfig.setRootProjectDir(layout.projectDir().toFile());
            incrementalConfig.setBuildDir(Files.createDirectories(layout.buildDir()).toFile());
            incrementalConfig.usePreciseJavaTracking(true);
            compilationConfig.useLogger(new KotlinCompilerSlf4jLogger(logCollector));

            return new KotlinCompileStep(
                    layout,
                    service,
                    strategyConfig,
                    compilationConfig,
                    scenarioDescriptor.sources().toList(),
                    List.copyOf(compilerClasspath)
            );
        } catch (Exception e) {
            throw new RuntimeException("Failed to setup Kotlin compiler", e);
        }
    }
}
