<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.qualityminds.lazyval.integration</groupId>
        <artifactId>integration-test-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>integration-test-kotlin</artifactId>
    <name>Integration Test Kotlin (Gradle)</name>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.2</version>
                <executions>
                    <!-- install all required dependencies for Gradle to a separate local m2-repo -->
                    <execution>
                        <id>install-parent-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../pom.xml</file>
                            <pomFile>${project.basedir}/../../pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                            <packaging>pom</packaging>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-core-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../core/target/lazyval-${project.version}.jar</file>
                            <pomFile>${project.basedir}/../../core/pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-processor-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../processor/target/lazyval-processor-${project.version}.jar</file>
                            <pomFile>${project.basedir}/../../processor/pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-ksp-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../ksp/target/lazyval-ksp-${project.version}.jar</file>
                            <pomFile>${project.basedir}/../../ksp/pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-utils-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../utils/target/lazyval-utils-${project.version}.jar</file>
                            <pomFile>${project.basedir}/../../utils/pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-testkit-for-gradle</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <configuration>
                            <file>${project.basedir}/../../testkit/target/lazyval-testkit-${project.version}.jar</file>
                            <pomFile>${project.basedir}/../../testkit/pom.xml</pomFile>
                            <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>gradle-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <skip>${skipTests}</skip>
                            <executable>${gradle.os.script}</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>clean</argument>
                                <argument>test</argument>
                                <argument>--info</argument>
                                <argument>--console=plain</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>window-scripts</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <gradle.os.script>gradlew.bat</gradle.os.script>
            </properties>
        </profile>
        <profile>
            <id>unix-scripts</id>
            <activation>
                <os>
                    <family>unix</family>
                </os>
            </activation>
            <properties>
                <gradle.os.script>./gradlew</gradle.os.script>
            </properties>
        </profile>
    </profiles>
</project>