= Lazyval: Compile-Time Code Generator for Domain Primitives in Java or Kotlin

== What is Lazyval / Motivation

Lazyval is a Java annotation processor & Kotlin symbol processor generating boilerplate code,
often needed when modeling _"Domain Primitives"_, which are simple, domain-specific wrapper types around primitives.
The initial idea was inspired by Scalas https://www.scala-lang.org/api/current/scala/AnyVal.html[Anyval];
even though this works completely differently, it allows you to easily define a domain-type which
encapsulates invariants.

NOTE: the term _"Domain Primitive"_ was taken from the book https://www.manning.com/books/secure-by-design[Secure by Design].

.Sample domain-primitive
[source, java]
----
public record Quantity(int value) {
    public Quantity {
        if (value < 0) {
            throw new IllegalArgumentException("Quantity must be greater than 0");
        }
    }
}
----

Unfortunately, this style of modeling requires additional work which is often seen as too much of a burden and proper
modeling falls short.
As an example, in a project with JPA: for each custom domain primitive, it is necessary to provide an additional
JPA AttributeConverter that is converting the type to a column and vice versa. JSON de/serializers also require
additional attention.

*Lazyval eliminates this burden by generating the necessary type-conversions. Furthermore, it will only generate
Classes for which the required dependencies are available on the classpath.*

* Currently supported

** Jackson 2 & 3 (xref:generators:jackson.adoc[Generator])

** JPA (xref:generators:jpa.adoc[Generator])

** Mapstruct (xref:generators:mapstruct.adoc[Generator])

* Future plans

** Spring Converters

** Cassandra

** MongoDb

NOTE: for custom generators, see xref:spi:index.adoc[Lazyvals SPI].

In addition, Lazyval tries to be smart in a way that it doesn't force any conventions on the code (like factory-methods
having to have a dedicated name). Instead, it tries to figure out as much as possible from the code and the current
classpath, which also reduces the amount of necessary configuration.

In a possible future, where Java value-types are released and fully supported by the
ecosystem, (meaning you can use a value-type in an JPA entity without hassle),
this project is probably not needed anymore.

== Usage

xref:java.adoc[Getting started with Java]

xref:kotlin.adoc[Getting started with Kotlin]

xref:multi-module.adoc[Multi-Module Support]

== Global Configuration Options

|===
|Property |Description

|_lazyval.generators.basePackage_
|When this option is set with the applications’ base package, the generators use sensible defaults where the generated artifacts should be located (following hexagonal architecture guidelines). See specific generator about defaults and how to override.
In case no basePackage nor generator-specific override is provided, the package of the first domain-primitive is used as
fallback (custom generators might choose a different strategy).

|_lazyval.generators.disable_
|Comma separated List of Generator-IDs that should not generate output despite being found on the classpath.
Active Generator-IDs are printed to the console during compilation.

|_lazyval.values_
|Comma separated List with FQNs for classes which are not part of the current compilation-unit,
but found on the classpath. See also xref:multi-module.adoc[Multi-Module Support].

|===

For generator-specific options, see the Generators section.


== License

This project is licensed under the [Apache License 2.0](LICENSE). You are free to use, modify, and distribute it under the terms of that license.

== Cyber Resilience Act (CRA) Notice

**Important Notice regarding the EU Cyber Resilience Act (CRA):**
This project is a *developer tool* and **does not constitute a "product with digital elements"** as defined under the CRA. It is not executed in production environments, nor does it process data during runtime.

The responsibility for the security, compliance, and correctness of the generated code lies entirely with the user. If the generated clients are used in safety-critical or regulated domains, users must perform their own security and compliance assessments.

== Disclaimer of Liability

This project provides templates and helper scripts on an "as-is" basis, without any warranties.

The maintainers do **not accept any liability** for:

- the security or correctness of generated code,
- suitability for use in any specific technical or regulatory context.

Use of this project is at your own risk. Always validate generated code in accordance with your organization’s quality and security standards.