= Java

[#usage]
== Usage

First, add the annotation and processor dependencies to your favorite build-tool. See below for <<setup>>.

Mark your domain-primitive with the `@LazyValue` annotation and the processor will figure out the rest.

.Quantity Record
[source,java]
----
include::ROOT:example$java/src/main/java/test/Quantity.java[tag=docu]
----

.ISBN Object with factory method
[source,java]
----
include::ROOT:example$java/src/main/java/test/Isbn.java[tag=docu]
----

[#setup]
== Setup

The following snippets only contain the relevant parts to set up and configure Lazyval.
The `jakarta-ee` dependency can be replaced by any that ships `jakarta-persistence`.
Keep in mind, Lazyval will only activate generators whose required dependencies are
available.

NOTE: These samples show the full setup, using the smallest dependencies. In case a feature is not needed, just remove
the dependency.

[tabs]
====
Maven::
+
.pom.xml
[source, xml]
----
include::ROOT:example$java/pom.xml[tags=docu;!excluded]
----
<1> mark the dependency as optional to avoid runtime-dependency

Maven 4::
+
Maven 4 changes the way the annotation-processor-classpath is set.
+
.pom.xml
[source, xml]
----
include::ROOT:example$java/pom-maven-4.xml[tags=docu;!excluded]
----
<1> mark the dependency as optional to avoid runtime-dependency
<2> annotation-processors have their own scope now

Gradle::
+
.build.gradle.kts
[source, kotlin]
----
include::ROOT:example$java/build.gradle.kts[tags=docu;!excluded]
----

Mill::
+
.build.mill
[source, scala]
----
include::ROOT:example$java/build.mill[tags=docu;!excluded]
----
====