= Kotlin Support via KSP2

For Kotlin, the original Java Annotation Processor was migrated to KSP2 (Kotlin Symbol Processing) to make use of
the `@LazyValue` annotation on Kotlin classes and data-classes.

[#usage]
== Usage

First, add the annotation and processor dependencies to your favorite build-tool. See below for <<setup>>.

NOTE: KSP2 only officially supports Gradle. Mill has its own KSP2 support. Maven users need to rely on
3rd-party plugins.

Mark your domain-primitive with the `@LazyValue` annotation and the processor will figure out the rest.

.Quantity Dataclass
[source, kotlin]
----
include::ROOT:example$kotlin/src/main/kotlin/test/Quantity.kt[tags=docu;!excluded]
----

.ISBN Object with factory method
[source,kotlin]
----
include::ROOT:example$kotlin/src/main/kotlin/test/Isbn.kt[tags=docu;!excluded]
----

IMPORTANT: The generated Mapstruct interface will still be a Java file because Mapstruct
is a Java Annotation Processor that cannot read Kotlin sources.

.Generated Mapper definition
[source,java]
----
@Mapper(
    unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface LazyvalMapper {
  default String mapIsbnToWrappedType(Isbn type) {
    if (type == null) {
      return null;
    }
    return type.value();
  }

  default Isbn mapIsbn(String value) {
    if (value == null) {
      return null;
    }
    return Isbn.parse(value);
  }

  default int mapQuantityToWrappedType(Quantity type) {
    return type.getValue();
  }

  default Quantity mapQuantity(int value) {
    return new Quantity(value);
  }
}
----


.Generated JPA AttributeConverter definition
[source, kotlin]
----
@Converter(autoApply = true)
public class IsbnAttributeConverter :  AttributeConverter<Isbn?, String?> {
  override fun convertToDatabaseColumn(type: Isbn?): String? = type?.value()

  override fun convertToEntityAttribute(dbValue: String?): Isbn? = dbValue?.let { Isbn.parse(dbValue) }
}

@Converter(autoApply = true)
public class QuantityAttributeConverter : AttributeConverter<Quantity?, Int?> {
  override fun convertToDatabaseColumn(type: Quantity?): Int? = type?.value

  override fun convertToEntityAttribute(dbValue: Int?): Quantity? = dbValue?.let { Quantity(dbValue) }
}
----

[#setup]
== Setup

The following snippets only contain the relevant parts to set up and configure Lazyval.
The `jakartaee-api` dependency can be replaced by any that ships `jakarta-persistence`.
Keep in mind, Lazyval will only activate generators whose required dependencies are
available.

[tabs]
====

Gradle::
+
.build.gradle.kts
[source, kotlin]
----
include::ROOT:example$kotlin/build.gradle.kts[tags=docu;!excluded]
----
+
.gradle.properties
[source, properties]
----
include::ROOT:example$kotlin/gradle.properties[]
----

Mill::
+
.build.mill
[source, scala]
----
include::ROOT:example$kotlin/build.mill[tags=docu;!excluded]
----

Maven::
+
There are currently two 3rd-party Maven plugins for KSP2: https://github.com/kpavlov/ksp-maven-plugin and https://github.com/mcarleio/ksp-maven-plugin
+
The following sample uses the kpavlovs.
+
.pom.xml
[source, xml]
----
include::ROOT:example$kotlin/pom.xml[tags=docu;!excluded]
----
<1> mark the dependency as optional to avoid runtime-dependency

====

