= Using the Lazyval SPI

To support users with the option to add custom code-generators, an SPI (service-provider-interface) has been added for each processor implementation.
In fact, the internal generators use the same mechanism and act as a reference implementation.

NOTE: the SPI also allows the project to hold new generators in an external incubation phase before shipping them
as part of the Lazyval bundle.

CAUTION: the SPI is currently experimental and will change!

First, you have to decide if you need a generator for Java (Annotation Processing) or Kotlin (KSP2). This is necessary
because the SPI has to leak the underlying processing API to the consumer.

Add the chosen processor as a dependency and implement the SPI.

.Java SPI
* https://github.com/QualityMinds/lazyval/blob/main/processor/src/main/java/com/qualityminds/lazyval/processor/spi/Generator.java[com.qualityminds.lazyval.processor.spi.Generator]

.Kotlin SPI
* https://github.com/QualityMinds/lazyval/blob/main/ksp/src/main/kotlin/com/qualityminds/lazyval/ksp/spi/SpiGenerators.kt[com.qualityminds.lazyval.ksp.spi.Generator]

To use a custom generator, it must be located in a separate JAR with a file named after the SPI in `META-INF/services/`
with the fully qualified name of your implementation. The JAR needs to be added to the compile-classpath (in some tools
called annotation-processor-classpath)

== Testing Providers

See xref:spi:testkit.adoc[Testkit] for a simple way to verify your custom implementation is working as expected.
