name: CI

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          # we compile with 25 but run all samples with 17
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Build and Install to Local Repository
        run: mvn --no-snapshot-updates --no-transfer-progress --batch-mode install --file pom.xml
      - name: Upload Lazyval Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
          retention-days: 1

  examples-java-maven:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 3 wrapper
        working-directory: examples/java
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
      - name: Run Java-Example with Maven
        working-directory: examples/java
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile
      - name: Uncomment type in source tree
        working-directory: examples/java
        # removes /* and */ from ProductName.java
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/java/test/ProductName.java
      - name: Run Incremental Compilation
        working-directory: examples/java
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile

  examples-java-maven-4:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 4 wrapper
        working-directory: examples/java
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=4.0.0-rc-5
      - name: Run Java-Example with Maven
        working-directory: examples/java
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile -f pom-maven-4.xml
      - name: Uncomment type in source tree
        working-directory: examples/java
        # removes /* and */ from ProductName.java
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/java/test/ProductName.java
      - name: Run Incremental Compilation
        working-directory: examples/java
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile -f pom-maven-4.xml

  examples-java-gradle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Run Java-Example with Gradle
        working-directory: examples/java
        run: gradle build
      - name: Uncomment type in source tree
        working-directory: examples/java
        # removes /* and */ from ProductName.java
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/java/test/ProductName.java
      - name: Run Incremental Compilation
        working-directory: examples/java
        run: gradle build

  examples-java-mill:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: coursier/cache-action@v7
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Download Mill Script
        working-directory: examples/java
        run: curl -L -s https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/${MILL_VERSION}/mill-dist-${MILL_VERSION}-mill.sh -o mill && chmod +x mill
        env:
          MILL_VERSION: 1.1.2
      - name: Run Java-Example with Mill
        working-directory: examples/java
        run: ./mill --no-daemon __.compile
      - name: Uncomment type in source tree
        working-directory: examples/java
        # removes /* and */ from ProductName.java
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/java/test/ProductName.java
      - name: Run Incremental Compilation
        working-directory: examples/java
        run: ./mill --no-daemon __.compile

  examples-kotlin-maven:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 3 wrapper
        working-directory: examples/kotlin
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
      - name: Run Java-Example with Maven
        working-directory: examples/kotlin
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile
      - name: Uncomment type in source tree
        working-directory: examples/kotlin
        # removes /* and */ from ProductName.kt
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/kotlin/test/ProductName.kt
      - name: Run Incremental Compilation
        working-directory: examples/kotlin
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile

  examples-kotlin-maven-4:
    if: false # disabled due to maven-compiler-plugin 4-beta not seeing compiled kotlin classes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 4 wrapper
        working-directory: examples/kotlin
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=4.0.0-rc-5
      - name: Run Java-Example with Maven
        working-directory: examples/kotlin
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile -f pom-maven-4.xml
      - name: Uncomment type in source tree
        working-directory: examples/kotlin
        # removes /* and */ from ProductName.kt
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/kotlin/test/ProductName.kt
      - name: Run Incremental Compilation
        working-directory: examples/kotlin
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile -f pom-maven-4.xml

  examples-kotlin-gradle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Run Kotlin-Example with Gradle
        working-directory: examples/kotlin
        run: gradle build
      - name: Uncomment type in source tree
        working-directory: examples/kotlin
        # removes /* and */ from ProductName.kt
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/kotlin/test/ProductName.kt
      - name: Run Incremental Compilation
        working-directory: examples/kotlin
        run: gradle build

  examples-kotlin-mill:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: coursier/cache-action@v7
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Download Mill Script
        working-directory: examples/kotlin
        run: curl -L -s https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/${MILL_VERSION}/mill-dist-${MILL_VERSION}-mill.sh -o mill && chmod +x mill
        env:
          MILL_VERSION: 1.1.0
      - name: Run Kotlin-Example with Mill
        working-directory: examples/kotlin
        run: ./mill --no-daemon __.compile
      - name: Uncomment type in source tree
        working-directory: examples/kotlin
        # removes /* and */ from ProductName.kt
        run: sed -i '/^\/\*$/d; /^\*\/$/d' src/main/kotlin/test/ProductName.kt
      - name: Run Incremental Compilation
        working-directory: examples/kotlin
        run: ./mill --no-daemon __.compile

  examples-java-spi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 3 wrapper
        working-directory: examples/java-spi-dev
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
      - name: Run Java-Example with Maven
        working-directory: examples/java-spi-dev
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile

  examples-kotlin-spi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download Lazyval Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-repo-lazyval
          path: ~/.m2/repository/de/qualityminds/lazyval
      - name: Create Maven 3 wrapper
        working-directory: examples/kotlin-spi-dev
        run: mvn --no-transfer-progress -N wrapper:wrapper -Dmaven=3.9.12
      - name: Run Java-Example with Maven
        working-directory: examples/kotlin-spi-dev
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode compile
