name: Publish Documentation

on:
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @antora/cli@3.1 @antora/site-generator@3.1 @antora/collector-extension@1.0 @asciidoctor/tabs

      - name: Generate Site
        run: npx antora antora-playbook.yml

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/site

  deploy:
    name: Deploy Docs
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5