name: Publish Snapshot

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  JAVA_VERSION: '25'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  verify-ci:
    name: Verify Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Verify CI passed
        uses: ./.github/actions/verify-ci-passed

  publish:
    name: Publish Snapshot
    needs: verify-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          CENTRAL_USERNAME: ${{ secrets.MAVEN_USERTOKEN_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.MAVEN_USERTOKEN_PASSPHRASE }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: ./mvnw --no-snapshot-updates --no-transfer-progress --batch-mode -DskipTests -Ppublish deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.MAVEN_USERTOKEN_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.MAVEN_USERTOKEN_PASSPHRASE }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}