name: Publish Snapshot

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/maven.yml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: GPG_PRIVATE_KEY
          gpg-passphrase: GPG_PASSPHRASE
        env:
          CENTRAL_USERNAME: ${{ secrets.MAVEN_USERTOKEN_PASSPHRASE }}
          CENTRAL_TOKEN: ${{ secrets.MAVEN_USERTOKEN_USERNAME }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Deploy to Maven
        run: ./mvnw -DskipTest -Ppublish deploy