name: Reduce README
on:
  push:
    paths:
      - _documentation/README.source.adoc
      - _documentation/README-Kotlin.source.adoc
    branches: ['**']
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer
      - name: Reduce Java README
        run: asciidoctor-reducer --preserve-conditionals -o README.adoc _documentation/README.source.adoc
      - name: Reduce Kotlin README
        run: asciidoctor-reducer --preserve-conditionals -o README-Kotlin.adoc _documentation/README-Kotlin.source.adoc
      - name: Commit and Push README
        uses: EndBug/add-and-commit@v9
        with:
          add: README.adoc README-Kotlin.adoc
